//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.Web.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class evaluate
    {
        public int EvaluateId { get; set; }
        public int MenuId { get; set; }
        public string Evaluate1 { get; set; }
    }
}
