//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.Web.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> CuisineId { get; set; }
        public Nullable<int> Money { get; set; }
        public Nullable<int> Kg { get; set; }
        public string Img { get; set; }
        public string CookingSteps { get; set; }
        public string trait { get; set; }
        public string miaoshu { get; set; }
        public Nullable<int> tuijian { get; set; }
        public Nullable<int> liulanliang { get; set; }
    }
}
